inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rspec_rails

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

# スタイル関連
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/FetchEnvVar:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

# メトリクス関連
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'app/controllers/**/*'

Metrics/AbcSize:
  Max: 50

# レイアウト関連
Layout/LineLength:
  Max: 180
  Exclude:
    - 'spec/**/*'

# Rails関連
Rails/FilePath:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Rails/ActionOrder:
  Enabled: true

# RSpec関連
RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 15

RSpec/ContextWording:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 7

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/PredicateMatcher:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: true

Rails/EagerEvaluationLogMessage:
  Enabled: true
