# fly.toml app configuration file generated for ecs-4 on 2024-12-26T17:24:13+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ecs-4'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = "3000"
  RAILS_ENV = "production"
  RACK_ENV = "production"
  RAILS_SERVE_STATIC_FILES = "true"


[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false  # 変更
  auto_start_machines = true
  min_machines_running = 1    # 変更
  processes = ['app']

[[vm]]
  size = 'shared-cpu-2x'
