一般社団法人 救急振興財団　<br>
応急手当講習テキスト（ガイドライン 2020対応）　参照
```mermaid
flowchart LR
    A["応急手当"] --> B["救命処置"]
    A --> C["その他の応急手当(ファーストエイド)"]
    
    B --> D["呼吸や心臓が止まったとき"]
    B --> E["のどにものが詰まったとき"]
    
    D --> F["心肺蘇生(胸骨圧迫と人工呼吸など)"]
    D --> G["AEDの使用"]
    
    E --> H["気道異物の除去(背部叩打法など)"]
  
    C --> I["・楽な姿勢をとらせる方法（保温、体位など）
<br>・出血に対する応急手当（止血法）
<br>・気管支喘息発作に対する応急手当
<br>・アナフィラキシーに対する応急手当
<br>・低血糖に対する応急手当
<br>・けいれんに対する応急手当
<br>・失神に対する応急手当
<br>・熱中症に対する応急手当
<br>・低体温症に対する応急手当
<br>・きずに対する応急手当
<br>・ねんざ・打ち身（打撲）に対する応急手当
<br>・骨折に対する応急手当
<br>・首を痛めている場合の応急手当
<br>・やけど（熱傷）に対する応急手当
<br>・歯の損傷に対する応急手当
<br>・毒物に対する応急手当
<br>・溺水（水の事故）に対する応急手当
<br>・傷病者の運び方（搬送法）"]
```